### ISSUE TITLE
Bleadperl breaks BDFOY/Roman-Unicode-1.031.tar.gz

### ISSUE THREAD

**Issue by andk** [briandfoy/Roman-Unicode#1]
Cross reference: https://rt.perl.org/Public/Bug/Display.html?id=133860

**Comment by jkeenan** [comment]
See, e.g., http://www.cpantesters.org/cpan/report/d2bd5332-436b-11e9-9c4c-d533cbdd0b6f

Sample output of ```prove```:
```
t/numbers.t ....... 
ok 1 - use Roman::Unicode;
ok 2 - Ⅰ is roman
ok 3 - Ⅰ is 1
ok 4 - 1 is Ⅰ
...
ok 35 - ⅯⅭⅮⅩⅬⅠⅤ is roman
ok 36 - ⅯⅭⅮⅩⅬⅠⅤ is 1444
ok 37 - 1444 is ⅯⅭⅮⅩⅬⅠⅤ
ok 38 - ⅯⅯⅤⅠⅠ is roman
ok 39 - ⅯⅯⅤⅠⅠ is 2007
ok 40 - 2007 is ⅯⅯⅤⅠⅠ
panic: memory wrap at t/numbers.t line 55.
# Tests were run but no plan was declared and done_testing() was not seen.
# Looks like your test exited with 255 just after 40.
Dubious, test returned 255 (wstat 65280, 0xff00)
All 40 subtests passed 
```

**Comment by khwilliamson** [comment]
I have investigated this issue enough that I'm pretty certain this stems from a core perl bug, and that fixing it will not involve  changes to the code in this module.

**Comment by jkeenan** [comment]
http://matrix.cpantesters.org/?dist=Roman-Unicode+1.031 suggests that the problem with Roman-Unicode is no longer present in 5.30 and subsequent releases.

brian, do you agree?

Thank you very much.
Jim Keenan
